include:
  - template: Auto-DevOps.gitlab-ci.yml

deploy:
  stage: production
  environment: production
  when: manual
  only:
    - main
  image: node:latest
  script:
    - npm install
    - npm run api:deploy
